openapi: 3.2.0
info:
  title: Dropbox API Reference Sharing API
  description: The powerful, yet simple, Dropbox API allows you to manage and control content and team settings programmatically and extend Dropbox capabilities in new and powerful ways.
  version: 1.0.0
servers:
- url: https://api.dropbox.com
security:
- bearerAuth: []
tags:
- name: Sharing
  description: This namespace contains endpoints and data types for creating and managing shared links and shared folders.
paths:
  /2/sharing/add_file_member:
    post:
      tags:
      - Sharing
      summary: Dropbox add_file_member
      description: 'add_file_member


        scope: `sharing.write`


        Adds specified members to a file.'
      operationId: post2SharingAddFileMember
      x-operation-id-source: derived
  /2/sharing/add_folder_member:
    post:
      tags:
      - Sharing
      summary: Dropbox add_folder_member
      description: 'add_folder_member


        scope: `sharing.write`


        Allows an owner or editor (if the ACL update policy allows) of a shared folder to add another member.

        For the new member to get access to all the functionality for this folder, you will need to call `mount_folder` on their behalf.'
      operationId: post2SharingAddFolderMember
      x-operation-id-source: derived
  /2/sharing/check_job_status:
    post:
      tags:
      - Sharing
      summary: Dropbox check_job_status
      description: 'check_job_status


        scope: `sharing.write`


        Returns the status of an asynchronous job.'
      operationId: post2SharingCheckJobStatus
      x-operation-id-source: derived
  /2/sharing/check_remove_member_job_status:
    post:
      tags:
      - Sharing
      summary: Dropbox check_remove_member_job_status
      description: 'check_remove_member_job_status


        scope: `sharing.write`


        Returns the status of an asynchronous job for sharing a folder.'
      operationId: post2SharingCheckRemoveMemberJobStatus
      x-operation-id-source: derived
  /2/sharing/check_share_job_status:
    post:
      tags:
      - Sharing
      summary: Dropbox check_share_job_status
      description: 'check_share_job_status


        scope: `sharing.write`


        Returns the status of an asynchronous job for sharing a folder.'
      operationId: post2SharingCheckShareJobStatus
      x-operation-id-source: derived
  /2/sharing/get_file_metadata:
    post:
      tags:
      - Sharing
      summary: Dropbox get_file_metadata
      description: 'get_file_metadata


        scope: `sharing.read`


        Returns shared file metadata.'
      operationId: post2SharingGetFileMetadata
      x-operation-id-source: derived
  /2/sharing/get_file_metadata/batch:
    post:
      tags:
      - Sharing
      summary: Dropbox get_file_metadata/batch
      description: 'get_file_metadata/batch


        scope: `sharing.read`


        Returns shared file metadata.'
      operationId: post2SharingGetFileMetadataBatch
      x-operation-id-source: derived
  /2/sharing/get_folder_metadata:
    post:
      tags:
      - Sharing
      summary: Dropbox get_folder_metadata
      description: 'get_folder_metadata


        scope: `sharing.read`


        Returns shared folder metadata by its folder ID.'
      operationId: post2SharingGetFolderMetadata
      x-operation-id-source: derived
  /2/sharing/get_shared_link_file:
    post:
      tags:
      - Sharing
      summary: Dropbox get_shared_link_file
      description: 'get_shared_link_file


        scope: `sharing.read`


        Download the shared link''s file from a user''s Dropbox.'
      operationId: post2SharingGetSharedLinkFile
      x-operation-id-source: derived
  /2/sharing/get_shared_link_metadata:
    post:
      tags:
      - Sharing
      summary: Dropbox get_shared_link_metadata
      description: 'get_shared_link_metadata


        scope: `sharing.read`


        Get the shared link''s metadata.'
      operationId: post2SharingGetSharedLinkMetadata
      x-operation-id-source: derived
  /2/sharing/list_file_members:
    post:
      tags:
      - Sharing
      summary: Dropbox list_file_members
      description: 'list_file_members


        scope: `sharing.read`


        Use to obtain the members who have been invited to a file, both inherited and uninherited members.'
      operationId: post2SharingListFileMembers
      x-operation-id-source: derived
  /2/sharing/list_file_members/batch:
    post:
      tags:
      - Sharing
      summary: Dropbox list_file_members/batch
      description: 'list_file_members/batch


        scope: `sharing.read`


        Get members of multiple files at once. The arguments to this route are more limited, and the limit on query result size per file is more strict. To customize the results more, use the individual file endpoint.

        Inherited users and groups are not included in the result, and permissions are not returned for this endpoint.'
      operationId: post2SharingListFileMembersBatch
      x-operation-id-source: derived
  /2/sharing/list_file_members/continue:
    post:
      tags:
      - Sharing
      summary: Dropbox list_file_members/continue
      description: 'list_file_members/continue


        scope: `sharing.read`


        Once a cursor has been retrieved from `list_file_members` or `list_file_members/batch`, use this to paginate through all shared file members.'
      operationId: post2SharingListFileMembersContinue
      x-operation-id-source: derived
  /2/sharing/list_folder_members/continue:
    post:
      tags:
      - Sharing
      summary: Dropbox list_folder_members/continue
      description: 'list_folder_members/continue


        scope: `sharing.read`


        Once a cursor has been retrieved from `list_folder_members`, use this to paginate through all shared folder members.'
      operationId: post2SharingListFolderMembersContinue
      x-operation-id-source: derived
  /2/sharing/list_folders:
    post:
      tags:
      - Sharing
      summary: Dropbox list_folders
      description: 'list_folders


        scope: `sharing.read`


        Return the list of all shared folders the current user has access to.'
      operationId: post2SharingListFolders
      x-operation-id-source: derived
  /2/sharing/list_folders/continue:
    post:
      tags:
      - Sharing
      summary: Dropbox list_folders/continue
      description: 'list_folders/continue


        scope: `sharing.read`


        Once a cursor has been retrieved from `list_folders`, use this to paginate through all shared folders. The cursor must come from a previous call to `list_folders` or `list_folders/continue`.'
      operationId: post2SharingListFoldersContinue
      x-operation-id-source: derived
  /2/sharing/list_mountable_folders:
    post:
      tags:
      - Sharing
      summary: Dropbox list_mountable_folders
      description: 'list_mountable_folders


        scope: `sharing.read`


        Return the list of all shared folders the current user can mount or unmount.'
      operationId: post2SharingListMountableFolders
      x-operation-id-source: derived
  /2/sharing/list_mountable_folders/continue:
    post:
      tags:
      - Sharing
      summary: Dropbox list_mountable_folders/continue
      description: 'list_mountable_folders/continue


        scope: `sharing.read`


        Once a cursor has been retrieved from `list_mountable_folders`, use this to paginate through all mountable shared folders. The cursor must come from a previous call to `list_mountable_folders` or `list_mountable_folders/continue`.'
      operationId: post2SharingListMountableFoldersContinue
      x-operation-id-source: derived
  /2/sharing/list_received_files:
    post:
      tags:
      - Sharing
      summary: Dropbox list_received_files
      description: 'list_received_files


        scope: `sharing.read`


        Returns a list of all files shared with current user.

        Does not include files the user has received via shared folders, and does not include unclaimed invitations.'
      operationId: post2SharingListReceivedFiles
      x-operation-id-source: derived
  /2/sharing/list_received_files/continue:
    post:
      tags:
      - Sharing
      summary: Dropbox list_received_files/continue
      description: 'list_received_files/continue


        scope: `sharing.read`


        Get more results with a cursor from `list_received_files`.'
      operationId: post2SharingListReceivedFilesContinue
      x-operation-id-source: derived
  /2/sharing/list_shared_links:
    post:
      tags:
      - Sharing
      summary: Dropbox list_shared_links
      description: 'list_shared_links


        scope: `sharing.read`


        List shared links of this user.

        If no path is given, returns a list of all shared links for the current user.

        If a non-empty path is given, returns a list of all shared links that allow access to the given path - direct links to the given path and links to parent folders of the given path. Links to parent folders can be suppressed by setting direct_only to true.'
      operationId: post2SharingListSharedLinks
      x-operation-id-source: derived
  /2/sharing/modify_shared_link_settings:
    post:
      tags:
      - Sharing
      summary: Dropbox modify_shared_link_settings
      description: 'modify_shared_link_settings


        scope: `sharing.write`


        Modify the shared link''s settings.

        If the requested visibility conflict with the shared links policy of the team or the shared folder (in case the linked file is part of a shared folder) then the `LinkPermissions.resolved_visibility` of the returned `SharedLinkMetadata` will reflect the actual visibility of the shared link and the `LinkPermissions.requested_visibility` will reflect the requested visibility.'
      operationId: post2SharingModifySharedLinkSettings
      x-operation-id-source: derived
  /2/sharing/mount_folder:
    post:
      tags:
      - Sharing
      summary: Dropbox mount_folder
      description: 'mount_folder


        scope: `sharing.write`


        The current user mounts the designated folder.

        Mount a shared folder for a user after they have been added as a member. Once mounted, the shared folder will appear in their Dropbox.'
      operationId: post2SharingMountFolder
      x-operation-id-source: derived
  /2/sharing/relinquish_file_membership:
    post:
      tags:
      - Sharing
      summary: Dropbox relinquish_file_membership
      description: 'relinquish_file_membership


        scope: `sharing.write`


        The current user relinquishes their membership in the designated file. Note that the current user may still have inherited access to this file through the parent folder.'
      operationId: post2SharingRelinquishFileMembership
      x-operation-id-source: derived
  /2/sharing/relinquish_folder_membership:
    post:
      tags:
      - Sharing
      summary: Dropbox relinquish_folder_membership
      description: 'relinquish_folder_membership


        scope: `sharing.write`


        The current user relinquishes their membership in the designated shared folder and will no longer have access to the folder. A folder owner cannot relinquish membership in their own folder.

        This will run synchronously if leave_a_copy is false, and asynchronously if leave_a_copy is true.'
      operationId: post2SharingRelinquishFolderMembership
      x-operation-id-source: derived
  /2/sharing/remove_file_member_2:
    post:
      tags:
      - Sharing
      summary: Dropbox remove_file_member_2
      description: 'remove_file_member_2


        scope: `sharing.write`


        Removes a specified member from the file.'
      operationId: post2SharingRemoveFileMember2
      x-operation-id-source: derived
  /2/sharing/remove_folder_member:
    post:
      tags:
      - Sharing
      summary: Dropbox remove_folder_member
      description: 'remove_folder_member


        scope: `sharing.write`


        Allows an owner or editor (if the ACL update policy allows) of a shared folder to remove another member.'
      operationId: post2SharingRemoveFolderMember
      x-operation-id-source: derived
  /2/sharing/revoke_shared_link:
    post:
      tags:
      - Sharing
      summary: Dropbox revoke_shared_link
      description: 'revoke_shared_link


        scope: `sharing.write`


        Revoke a shared link.

        Note that even after revoking a shared link to a file, the file may be accessible if there are shared links leading to any of the file parent folders. To list all shared links that enable access to a specific file, you can use the `list_shared_links` with the file as the `ListSharedLinksArg.path` argument.'
      operationId: post2SharingRevokeSharedLink
      x-operation-id-source: derived
  /2/sharing/set_access_inheritance:
    post:
      tags:
      - Sharing
      summary: Dropbox set_access_inheritance
      description: 'set_access_inheritance


        scope: `sharing.write`


        Change the inheritance policy of an existing Shared Folder. Only permitted for shared folders in a shared team root.

        If a `ShareFolderLaunch.async_job_id` is returned, you''ll need to call `check_share_job_status` until the action completes to get the metadata for the folder.'
      operationId: post2SharingSetAccessInheritance
      x-operation-id-source: derived
  /2/sharing/share_folder:
    post:
      tags:
      - Sharing
      summary: Dropbox share_folder
      description: 'share_folder


        scope: `sharing.write`


        Share a folder with collaborators.

        Most sharing will be completed synchronously. Large folders will be completed asynchronously. To make testing the async case repeatable, set `ShareFolderArg.force_async`.

        If a `ShareFolderLaunch.async_job_id` is returned, you''ll need to call `check_share_job_status` until the action completes to get the metadata for the folder.'
      operationId: post2SharingShareFolder
      x-operation-id-source: derived
  /2/sharing/transfer_folder:
    post:
      tags:
      - Sharing
      summary: Dropbox transfer_folder
      description: 'transfer_folder


        scope: `sharing.write`


        Transfer ownership of a shared folder to a member of the shared folder.

        User must have `AccessLevel.owner` access to the shared folder to perform a transfer.'
      operationId: post2SharingTransferFolder
      x-operation-id-source: derived
  /2/sharing/unmount_folder:
    post:
      tags:
      - Sharing
      summary: Dropbox unmount_folder
      description: 'unmount_folder


        scope: `sharing.write`


        The current user unmounts the designated folder. They can re-mount the folder at a later time using `mount_folder`.'
      operationId: post2SharingUnmountFolder
      x-operation-id-source: derived
  /2/sharing/unshare_file:
    post:
      tags:
      - Sharing
      summary: Dropbox unshare_file
      description: 'unshare_file


        scope: `sharing.write`


        Remove all members from this file. Does not remove inherited members.'
      operationId: post2SharingUnshareFile
      x-operation-id-source: derived
  /2/sharing/unshare_folder:
    post:
      tags:
      - Sharing
      summary: Dropbox unshare_folder
      description: 'unshare_folder


        scope: `sharing.write`


        Allows a shared folder owner to unshare the folder.

        You''ll need to call `check_job_status` to determine if the action has completed successfully.'
      operationId: post2SharingUnshareFolder
      x-operation-id-source: derived
  /2/sharing/update_file_member:
    post:
      tags:
      - Sharing
      summary: Dropbox update_file_member
      description: 'update_file_member


        scope: `sharing.write`


        Changes a member''s access on a shared file.'
      operationId: post2SharingUpdateFileMember
      x-operation-id-source: derived
  /2/sharing/update_folder_member:
    post:
      tags:
      - Sharing
      summary: Dropbox update_folder_member
      description: 'update_folder_member


        scope: `sharing.write`


        Allows an owner or editor of a shared folder to update another member''s permissions.'
      operationId: post2SharingUpdateFolderMember
      x-operation-id-source: derived
  /2/sharing/update_folder_policy:
    post:
      tags:
      - Sharing
      summary: Dropbox update_folder_policy
      description: 'update_folder_policy


        scope: `sharing.write`


        Update the sharing policies for a shared folder.

        User must have `AccessLevel.owner` access to the shared folder to update its policies.'
      operationId: post2SharingUpdateFolderPolicy
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
