openapi: 3.2.0
info:
  title: Dropbox API Reference File Properties API
  description: The powerful, yet simple, Dropbox API allows you to manage and control content and team settings programmatically and extend Dropbox capabilities in new and powerful ways.
  version: 1.0.0
servers:
- url: https://api.dropbox.com
security:
- bearerAuth: []
tags:
- name: File_properties
  description: This namespace contains helpers for property and template metadata endpoints.
paths:
  /2/file_properties/properties/add:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/add
      description: 'properties/add


        scope: `files.metadata.write`


        Add property groups to a Dropbox file. See `templates/add_for_user` or `templates/add_for_team` to create new templates.'
      operationId: post2FilePropertiesPropertiesAdd
      x-operation-id-source: derived
  /2/file_properties/properties/overwrite:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/overwrite
      description: 'properties/overwrite


        scope: `files.metadata.write`


        Overwrite property groups associated with a file. This endpoint should be used instead of `properties/update` when property groups are being updated via a "snapshot" instead of via a "delta". In other words, this endpoint will delete all omitted fields from a property group, whereas `properties/update` will only delete fields that are explicitly marked for deletion.'
      operationId: post2FilePropertiesPropertiesOverwrite
      x-operation-id-source: derived
  /2/file_properties/properties/remove:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/remove
      description: 'properties/remove


        scope: `files.metadata.write`


        Permanently removes the specified property group from the file. To remove specific property field key value pairs, see `properties/update`. To update a template, see `templates/update_for_user` or `templates/update_for_team`. To remove a template, see `templates/remove_for_user` or `templates/remove_for_team`.'
      operationId: post2FilePropertiesPropertiesRemove
      x-operation-id-source: derived
  /2/file_properties/properties/search:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/search
      description: 'properties/search


        scope: `files.metadata.read`


        Search across property templates for particular property field values.'
      operationId: post2FilePropertiesPropertiesSearch
      x-operation-id-source: derived
  /2/file_properties/properties/search/continue:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/search/continue
      description: 'properties/search/continue


        scope: `files.metadata.read`


        Once a cursor has been retrieved from `properties/search`, use this to paginate through all search results.'
      operationId: post2FilePropertiesPropertiesSearchContinue
      x-operation-id-source: derived
  /2/file_properties/properties/update:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/update
      description: 'properties/update


        scope: `files.metadata.write`


        Add, update or remove properties associated with the supplied file and templates. This endpoint should be used instead of `properties/overwrite` when property groups are being updated via a "delta" instead of via a "snapshot" . In other words, this endpoint will not delete any omitted fields from a property group, whereas `properties/overwrite` will delete any fields that are omitted from a property group.'
      operationId: post2FilePropertiesPropertiesUpdate
      x-operation-id-source: derived
  /2/file_properties/templates/add_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/add_for_team
      description: 'templates/add_for_team


        scope: `files.team_metadata.write`


        Add a template associated with a team. See `properties/add` to add properties to a file or folder.

        Note: this endpoint will create team-owned templates.'
      security:
      - bearerAuth: []
      operationId: post2FilePropertiesTemplatesAddForTeam
      x-operation-id-source: derived
  /2/file_properties/templates/add_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/add_for_user
      description: 'templates/add_for_user


        scope: `files.metadata.write`


        Add a template associated with a user. See `properties/add` to add properties to a file. This endpoint can''t be called on a team member or admin''s behalf.'
      operationId: post2FilePropertiesTemplatesAddForUser
      x-operation-id-source: derived
  /2/file_properties/templates/get_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/get_for_team
      description: 'templates/get_for_team


        scope: `files.team_metadata.write`


        Get the schema for a specified template.'
      security:
      - bearerAuth: []
      operationId: post2FilePropertiesTemplatesGetForTeam
      x-operation-id-source: derived
  /2/file_properties/templates/get_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/get_for_user
      description: 'templates/get_for_user


        scope: `files.metadata.read`


        Get the schema for a specified template. This endpoint can''t be called on a team member or admin''s behalf.'
      operationId: post2FilePropertiesTemplatesGetForUser
      x-operation-id-source: derived
  /2/file_properties/templates/list_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/list_for_team
      description: 'templates/list_for_team


        scope: `files.team_metadata.write`


        Get the template identifiers for a team. To get the schema of each template use `templates/get_for_team`.'
      security:
      - bearerAuth: []
      operationId: post2FilePropertiesTemplatesListForTeam
      x-operation-id-source: derived
  /2/file_properties/templates/list_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/list_for_user
      description: 'templates/list_for_user


        scope: `files.metadata.read`


        Get the template identifiers for a team. To get the schema of each template use `templates/get_for_user`. This endpoint can''t be called on a team member or admin''s behalf.'
      operationId: post2FilePropertiesTemplatesListForUser
      x-operation-id-source: derived
  /2/file_properties/templates/remove_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/remove_for_team
      description: 'templates/remove_for_team


        scope: `files.team_metadata.write`


        Permanently removes the specified template created from `templates/add_for_user`. All properties associated with the template will also be removed. This action cannot be undone.'
      security:
      - bearerAuth: []
      operationId: post2FilePropertiesTemplatesRemoveForTeam
      x-operation-id-source: derived
  /2/file_properties/templates/remove_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/remove_for_user
      description: 'templates/remove_for_user


        scope: `files.metadata.write`


        Permanently removes the specified template created from `templates/add_for_user`. All properties associated with the template will also be removed. This action cannot be undone.'
      operationId: post2FilePropertiesTemplatesRemoveForUser
      x-operation-id-source: derived
  /2/file_properties/templates/update_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/update_for_team
      description: 'templates/update_for_team


        scope: `files.team_metadata.write`


        Update a template associated with a team. This route can update the template name, the template description and add optional properties to templates.'
      security:
      - bearerAuth: []
      operationId: post2FilePropertiesTemplatesUpdateForTeam
      x-operation-id-source: derived
  /2/file_properties/templates/update_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/update_for_user
      description: 'templates/update_for_user


        scope: `files.metadata.write`


        Update a template associated with a user. This route can update the template name, the template description and add optional properties to templates. This endpoint can''t be called on a team member or admin''s behalf.'
      operationId: post2FilePropertiesTemplatesUpdateForUser
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
