openapi: 3.0.0
info:
  title: Dropbox API Reference Account Team > Members API
  description: "The powerful, yet simple, Dropbox API allows you to manage and control content and team settings programmatically and extend Dropbox capabilities in new and powerful ways. This is a collection that includes requests to all endpoints in the Dropbox API. \n\nThe Dropbox API is divided in two groups of endpoints: User Endpoints and Business Endpoints. Operations that would most likely be executed by a user, such as file operations, are in the User Endpoints folder. Operations that w[...]"
  version: 1.0.0
servers:
- url: https://api.dropbox.com
security:
- bearerAuth: []
tags:
- name: Team > Members
paths:
  /2/team/members/add:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/add
      description: '[members/add](https://www.dropbox.com/developers/documentation/http/teams#team-members-add)


        scope: `members.write`


        Adds members to a team.

        Permission : Team member management

        A maximum of 20 members can be specified in a single call.

        If no Dropbox account exists with the email address specified, a new Dropbox account will be created with the given email address, and that account will be invited to the team.

        If a personal Dropbox account exists with the email address specified in the call, this call will create a placeholder Dropbox account for the user on the team and send an email inviting the user to migrate their existing personal account onto the team.

        Team member management apps are required to set an initial given_name and surname for a user to use in the team invitation and for ''Perform as team member'' actions taken on the user before they become ''active''.'
  /2/team/members/add/job_status/get:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/add/job_status/get
      description: '[members/add/job_status/get](https://www.dropbox.com/developers/documentation/http/teams#team-members-add-job_status-get)


        scope: `members.write`


        Once an async_job_id is returned from `members/add` , use this to poll the status of the asynchronous request.

        Permission : Team member management.'
  /2/team/members/delete_profile_photo:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/delete_profile_photo
      description: '[members/delete_profile_photo](https://www.dropbox.com/developers/documentation/http/teams#team-members-delete_profile_photo)


        scope: `members.write`


        Deletes a team member''s profile photo.

        Permission : Team member management.'
  /2/team/members/get_info:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/get_info
      description: '[members/get_info](https://www.dropbox.com/developers/documentation/http/teams#team-members-get_info)


        scope: `members.read`


        Returns information about multiple team members.

        Permission : Team information

        This endpoint will return `MembersGetInfoItem.id_not_found`, for IDs (or emails) that cannot be matched to a valid team member.'
  /2/team/members/list:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/list
      description: '[members/list](https://www.dropbox.com/developers/documentation/http/teams#team-members-list)


        scope: `members.read`


        Lists members of a team.

        Permission : Team information.'
  /2/team/members/list/continue:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/list/continue
      description: '[members/list/continue](https://www.dropbox.com/developers/documentation/http/teams#team-members-list-continue)


        scope: `members.read`


        Once a cursor has been retrieved from `members/list`, use this to paginate through all team members.

        Permission : Team information.'
  /2/team/members/move_former_member_files:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/move_former_member_files
      description: '[members/move_former_member_files](https://www.dropbox.com/developers/documentation/http/teams#team-members-move_former_member_files)


        scope: `members.write`


        Moves removed member''s files to a different member. This endpoint initiates an asynchronous job. To obtain the final result of the job, the client should periodically poll `members/move_former_member_files/job_status/check`.

        Permission : Team member management.'
  /2/team/members/move_former_member_files/job_status/check:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/move_former_member_files/job_status/check
      description: '[members/move_former_member_files/job_status/check](https://www.dropbox.com/developers/documentation/http/teams#team-members-move_former_member_files-job_status-check)


        scope: `members.write`


        Once an async_job_id is returned from `members/move_former_member_files` , use this to poll the status of the asynchronous request.

        Permission : Team member management.'
  /2/team/members/recover:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/recover
      description: '[members/recover](https://www.dropbox.com/developers/documentation/http/teams#team-members-recover)


        scope: `members.delete`


        Recover a deleted member.

        Permission : Team member management

        Exactly one of team_member_id, email, or external_id must be provided to identify the user account.'
  /2/team/members/remove:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/remove
      description: '[members/remove](https://www.dropbox.com/developers/documentation/http/teams#team-members-remove)


        scope: `members.delete`


        Removes a member from a team.

        Permission : Team member management

        Exactly one of team_member_id, email, or external_id must be provided to identify the user account.

        Accounts can be recovered via `members/recover` for a 7 day period or until the account has been permanently deleted or transferred to another account (whichever comes first). Calling `members/add` while a user is still recoverable on your team will return with `MemberAddResult.user_already_on_team`.

        Accounts can have their files transferred via the admin console for a limited time, based on the version history length associated with the team (180 days for most teams).

        This endpoint may initiate an asynchronous job. To obtain the final result of the job, the client should periodically poll `members/remove/job_status/get`.'
  /2/team/members/remove/job_status/get:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/remove/job_status/get
      description: '[members/remove/job_status/get](https://www.dropbox.com/developers/documentation/http/teams#team-members-remove-job_status-get)


        scope: `members.delete`


        Once an async_job_id is returned from `members/remove` , use this to poll the status of the asynchronous request.

        Permission : Team member management.'
  /2/team/members/secondary_emails/add:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/secondary_emails/add
      description: '[members/secondary_emails/add](https://www.dropbox.com/developers/documentation/http/teams#team-members-secondary_emails-add)


        scope: `members.write`


        Add secondary emails to users.

        Permission : Team member management.

        Emails that are on verified domains will be verified automatically. For each email address not on a verified domain a verification email will be sent.'
  /2/team/members/secondary_emails/delete:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/secondary_emails/delete
      description: '[members/secondary_emails/delete](https://www.dropbox.com/developers/documentation/http/teams#team-members-secondary_emails-delete)


        scope: `members.write`


        Delete secondary emails from users

        Permission : Team member management.

        Users will be notified of deletions of verified secondary emails at both the secondary email and their primary email.'
  /2/team/members/secondary_emails/resend_verification_emails:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/secondary_emails/resend_verification_emails
      description: '[members/secondary_emails/resend_verification_emails](https://www.dropbox.com/developers/documentation/http/teams#team-members-secondary_emails-resend_verification_emails)


        scope: `members.write`


        Resend secondary email verification emails.

        Permission : Team member management.'
  /2/team/members/send_welcome_email:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/send_welcome_email
      description: '[members/send_welcome_email](https://www.dropbox.com/developers/documentation/http/teams#team-members-send_welcome_email)


        scope: `members.write`


        Sends welcome email to pending team member.

        Permission : Team member management

        Exactly one of team_member_id, email, or external_id must be provided to identify the user account.

        No-op if team member is not pending.'
  /2/team/members/set_admin_permissions:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/set_admin_permissions
      description: '[members/set_admin_permissions](https://www.dropbox.com/developers/documentation/http/teams#team-members-set_admin_permissions)


        scope: `members.write`


        Updates a team member''s permissions.

        Permission : Team member management.'
  /2/team/members/set_profile:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/set_profile
      description: '[members/set_profile](https://www.dropbox.com/developers/documentation/http/teams#team-members-set_profile)


        scope: `members.write`


        Updates a team member''s profile.

        Permission : Team member management.'
  /2/team/members/set_profile_photo:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/set_profile_photo
      description: '[members/set_profile_photo](https://www.dropbox.com/developers/documentation/http/teams#team-members-set_profile_photo)


        scope: `members.write`


        Updates a team member''s profile photo.

        Permission : Team member management.'
  /2/team/members/suspend:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/suspend
      description: '[members/suspend](https://www.dropbox.com/developers/documentation/http/teams#team-members-suspend)


        scope: `members.write`


        Suspend a member from a team.

        Permission : Team member management

        Exactly one of team_member_id, email, or external_id must be provided to identify the user account.'
  /2/team/members/unsuspend:
    post:
      tags:
      - Team > Members
      summary: Dropbox members/unsuspend
      description: '[members/unsuspend](https://www.dropbox.com/developers/documentation/http/teams#team-members-unsuspend)


        scope: `members.write`


        Unsuspend a member from a team.

        Permission : Team member management

        Exactly one of team_member_id, email, or external_id must be provided to identify the user account.'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
