openapi: 3.0.0
info:
  title: Dropbox API Reference Account File_properties API
  description: "The powerful, yet simple, Dropbox API allows you to manage and control content and team settings programmatically and extend Dropbox capabilities in new and powerful ways. This is a collection that includes requests to all endpoints in the Dropbox API. \n\nThe Dropbox API is divided in two groups of endpoints: User Endpoints and Business Endpoints. Operations that would most likely be executed by a user, such as file operations, are in the User Endpoints folder. Operations that w[...]"
  version: 1.0.0
servers:
- url: https://api.dropbox.com
security:
- bearerAuth: []
tags:
- name: File_properties
  description: 'This namespace contains helpers for property and template metadata endpoints.


    These endpoints enable you to tag arbitrary key/value data to Dropbox files.


    The most basic unit in this namespace is the :type:`PropertyField`. These fields encapsulate the actual key/value data.


    Fields are added to a Dropbox file using a :type:`PropertyGroup`. Property groups contain a reference to a Dropbox file and a :type:`PropertyGroupTemplate`. Property groups are uniquely identified by the combination of their associated Dropbox file and template.


    The :type:`PropertyGroupTemplate` is a way of restricting the possible key names and value types of the data within a property group. The possible key names and value types are explicitly enumerated using :type:`PropertyFieldTemplate` objects.


    You can think of a property group template as a class definition for a particular key/value metadata object, and the property groups themselves as the instantiations of these objects.


    Templates are owned either by a user/app pair or team/app pair. Templates and their associated properties can''t be accessed by any app other than the app that created them, and even then, only when the app is linked with the owner of the template (either a user or team).


    User-owned templates are accessed via the user-auth file_properties/templates/*_for_user endpoints, while team-owned templates are accessed via the team-auth file_properties/templates/*_for_team endpoints. Properties associated with either type of template can be accessed via the user-auth properties/* endpoints.


    Finally, properties can be accessed from a number of endpoints that return metadata, including `files/get_metadata`, and `files/list_folder`. Properties can also be added during upload, using `files/upload`.

    '
paths:
  /2/file_properties/properties/add:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/add
      description: '[properties/add](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-add)


        scope: `files.metadata.write`


        Add property groups to a Dropbox file. See `templates/add_for_user` or `templates/add_for_team` to create new templates.'
  /2/file_properties/properties/overwrite:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/overwrite
      description: '[properties/overwrite](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-overwrite)


        scope: `files.metadata.write`


        Overwrite property groups associated with a file. This endpoint should be used instead of `properties/update` when property groups are being updated via a "snapshot" instead of via a "delta". In other words, this endpoint will delete all omitted fields from a property group, whereas `properties/update` will only delete fields that are explicitly marked for deletion.'
  /2/file_properties/properties/remove:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/remove
      description: '[properties/remove](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-remove)


        scope: `files.metadata.write`


        Permanently removes the specified property group from the file. To remove specific property field key value pairs, see `properties/update`. To update a template, see `templates/update_for_user` or `templates/update_for_team`. To remove a template, see `templates/remove_for_user` or `templates/remove_for_team`.'
  /2/file_properties/properties/search:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/search
      description: '[properties/search](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-search)


        scope: `files.metadata.read`


        Search across property templates for particular property field values.'
  /2/file_properties/properties/search/continue:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/search/continue
      description: '[properties/search/continue](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-search-continue)


        scope: `files.metadata.read`


        Once a cursor has been retrieved from `properties/search`, use this to paginate through all search results.'
  /2/file_properties/properties/update:
    post:
      tags:
      - File_properties
      summary: Dropbox properties/update
      description: '[properties/update](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-update)


        scope: `files.metadata.write`


        Add, update or remove properties associated with the supplied file and templates. This endpoint should be used instead of `properties/overwrite` when property groups are being updated via a "delta" instead of via a "snapshot" . In other words, this endpoint will not delete any omitted fields from a property group, whereas `properties/overwrite` will delete any fields that are omitted from a property group.'
  /2/file_properties/templates/add_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/add_for_team
      description: '[templates/add_for_team](https://www.dropbox.com/developers/documentation/http/teams#file_properties-templates-add_for_team)


        scope: `files.team_metadata.write`


        Add a template associated with a team. See `properties/add` to add properties to a file or folder.

        Note: this endpoint will create team-owned templates.'
      security:
      - bearerAuth: []
  /2/file_properties/templates/add_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/add_for_user
      description: '[templates/add_for_user](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-templates-add_for_user)


        scope: `files.metadata.write`


        Add a template associated with a user. See `properties/add` to add properties to a file. This endpoint can''t be called on a team member or admin''s behalf.'
  /2/file_properties/templates/get_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/get_for_team
      description: '[templates/get_for_team](https://www.dropbox.com/developers/documentation/http/teams#file_properties-templates-get_for_team)


        scope: `files.team_metadata.write`


        Get the schema for a specified template.'
      security:
      - bearerAuth: []
  /2/file_properties/templates/get_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/get_for_user
      description: '[templates/get_for_user](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-templates-get_for_user)


        scope: `files.metadata.read`


        Get the schema for a specified template. This endpoint can''t be called on a team member or admin''s behalf.'
  /2/file_properties/templates/list_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/list_for_team
      description: '[templates/list_for_team](https://www.dropbox.com/developers/documentation/http/teams#file_properties-templates-list_for_team)


        scope: `files.team_metadata.write`


        Get the template identifiers for a team. To get the schema of each template use `templates/get_for_team`.      '
      security:
      - bearerAuth: []
  /2/file_properties/templates/list_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/list_for_user
      description: '[templates/list_for_user](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-templates-list_for_user)


        scope: `files.metadata.read`


        Get the template identifiers for a team. To get the schema of each template use `templates/get_for_user`. This endpoint can''t be called on a team member or admin''s behalf.      '
  /2/file_properties/templates/remove_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/remove_for_team
      description: '[templates/remove_for_team](https://www.dropbox.com/developers/documentation/http/teams#file_properties-templates-remove_for_team)


        scope: `files.team_metadata.write`


        Permanently removes the specified template created from `templates/add_for_user`. All properties associated with the template will also be removed. This action cannot be undone.'
      security:
      - bearerAuth: []
  /2/file_properties/templates/remove_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/remove_for_user
      description: '[templates/remove_for_user](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-templates-remove_for_user)


        scope: `files.metadata.write`


        Permanently removes the specified template created from `templates/add_for_user`. All properties associated with the template will also be removed. This action cannot be undone.'
  /2/file_properties/templates/update_for_team:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/update_for_team
      description: '[templates/update_for_team](https://www.dropbox.com/developers/documentation/http/teams#file_properties-templates-update_for_team)


        scope: `files.team_metadata.write`


        Update a template associated with a team. This route can update the template name, the template description and add optional properties to templates.'
      security:
      - bearerAuth: []
  /2/file_properties/templates/update_for_user:
    post:
      tags:
      - File_properties
      summary: Dropbox templates/update_for_user
      description: '[templates/update_for_user](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-templates-update_for_user)


        scope: `files.metadata.write`


        Update a template associated with a user. This route can update the template name, the template description and add optional properties to templates. This endpoint can''t be called on a team member or admin''s behalf.'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
